name: Publish Capacitor Android Plugin To NPM

on:
  release:
    types: [created]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                node-version: 20
                registry-url: https://registry.npmjs.org/
            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: 17
                distribution: 'temurin'
                cache: gradle
            - name: Grant execute permission for gradlew
              run: cd android && chmod +x gradlew
            - run: npm ci
            - name: Publish to NPM
              run: npm publish --access public
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
